# Generated by Django 3.1.2 on 2020-10-01 23:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20201001_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='transactions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
    ]
